name: main

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

env:
  LUA_LS_VERSION: 3.7.4

concurrency:
  group: github.head_ref
  cancel-in-progress: true

jobs:
  docs:
    runs-on: ubuntu-latest
    name: docs
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: setup neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: v0.9.4

      - name: generate docs
        run: make docs-ci

      - name: check docs diff
        run: exit $(git status --porcelain doc | wc -l | tr -d " ")
