name: main

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

env:
  LUA_LS_VERSION: 3.7.4

concurrency:
  group: github.head_ref
  cancel-in-progress: true

jobs:
  docs:
    runs-on: ubuntu-latest
    name: docs
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: setup neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: v0.9.4

      - name: generate docs
        run: make docs-ci

      - name: push changes
        uses: stefanzweifel/git-auto-commit-action@v5.0.0
        with:
          file_pattern: 'doc/*.txt'
          commit_message: "docs(build): auto-generate docs"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
